services:
  - type: web
    name: employee-salary-prediction-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: frontend/build